// angular-app/src/app/component/account/account.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {AccountService} from "../../service/account.service";
import {Router} from '@angular/router';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Account} from '../../model/account';
import {TranslateService} from "@ngstack/translate";

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class AccountComponent implements OnInit {

  pageTitle: string;
  submitted = false;
  accountForm: FormGroup;
  accessCode: string;
  debug: boolean = false;

  constructor(private accountService: AccountService,
              private router: Router,
              private formBuilder: FormBuilder,
              private translate: TranslateService) { }

  ngOnInit() {
    this.pageTitle = this.translate.get("title-account");
    if(this.accountService.isAuthenticated()){
      this.accountForm = this.formBuilder.group({
        email: [this.accountService.getAccount().email, [Validators.required, Validators.email]],
        language: [this.accountService.getAccount().language, Validators.required],
        name: [this.accountService.getAccount().name, Validators.required]
      });
      this.accessCode = this.accountService.getAccount()._id;

    }else{
      this.notAuthenticated();
    }
  }

  get form() {
    return this.accountForm.controls;
  }

  onSubmit() {
    this.submitted = true;

    if (this.accountForm.invalid) {
      return;
    }

    let account = new Account();
    account._id = this.accessCode;
    account.email = this.accountForm.value.email;
    account.language = this.accountForm.value.language;
    account.name = this.accountForm.value.name;

    this.accountService.update(account._id, account)
      .subscribe(account => {
          if(account){
            this.accountService.activeAccount = account;
            this.router.navigate(['/events']);
          }
      })
  }

  notAuthenticated(){
    this.router.navigate(['/']);
  }

}


<h2>{{pageTitle}}</h2>

<form [formGroup]="accountForm" (ngSubmit)="onSubmit()">
  <div class="form-group">
    <label>{{ 'field-name' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="name"
      name="name"
      formControlName="name"
      [ngClass]="{ 'is-invalid': submitted && form.name.errors }"
    />
    <div *ngIf="submitted && form.name.errors" class="invalid-feedback">
      <div *ngIf="form.name.errors.required">{{ 'field-name' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>
  <div class="form-group">
    <label>{{ 'field-email' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="email"
      name="email"
      formControlName="email"
      [ngClass]="{ 'is-invalid': submitted && form.email.errors }"
    />
    <div *ngIf="submitted && form.email.errors" class="invalid-feedback">
      {{ 'field-email' | translate }}{{ 'error-required' | translate }}
    </div>
  </div>
  <div class="form-group">
    <label>{{ 'field-accessCode' | translate }}</label>
    <div class="form-control no-border">
      <span>{{accessCode}}</span>
    </div>
  </div>

  <div class="form-group">
    <label>{{ 'field-language' | translate }}</label>
     <br />
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageEN"
          name="language"
          formControlName="language"
          value="en"
        />
        {{ 'language-en' | translate }}
      </label>
    </div>
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageNL"
          name="language"
          formControlName="language"
          value="nl"
        />
        {{ 'language-nl' | translate }}
      </label>
    </div>
    <div *ngIf="submitted && form.language.errors" class="invalid-feedback">
      <div *ngIf="form.language.errors.required">{{ 'field-langauge' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>

  <button type="submit" class="btn btn-success float-right">
    {{ 'button-update' | translate }}
  </button>
</form>

<div *ngIf="debug">
<p>Form value: {{ accountForm.value | json }}</p>
<p>Form status: {{ accountForm.status | json }}</p>
</div>

// vue-app/src/components/account.vue
<template>
    <div v-if="account">
        <h2>{{ $t('title-account') }}</h2>
        <div>
            <div class="form-group">
                <label>{{ $t('field-name') }}</label>
                <input
                        v-model="account.name"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validName}">
                <div class="invalid-feedback">{{ $t('field-name') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-email') }}</label>
                <input
                        v-model="account.email"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validEmail}">
                <div class="invalid-feedback">{{ $t('field-email') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-accessCode') }}</label>
                <div class="form-control no-border">
                    <span>{{account._id}}</span>
                </div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-language') }}</label>
                <br />
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="en"
                                name="language"
                                v-model="account.language"
                                value="en"
                        />
                        {{ $t('language-en') }}
                    </label>
                </div>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="nl"
                                name="language"
                                v-model="account.language"
                                value="nl"
                        />
                        {{ $t('language-nl') }}
                    </label>
                </div>

                <div class="invalid-feedback">{{ $t('field-language') }}{{ $t('error-required') }}</div>
            </div>

            <button type="submit" class="btn btn-success float-right" v-on:click.stop.prevent="submit">
                {{ $t('button-update') }}
            </button>

        </div>

        <div v-if="debug">{{account}}</div>
    </div>
</template>

<script>
    import {mapActions, mapState} from "vuex";

    export default {
        name: "account",
        data () {
            return {
                debug : true,
                valid : false,
                validEmail : true,
                validName : true,
                validLanguage : true
            }
        },
        computed: mapState({
            isAuthenticated : state => state.account.authenticated,
            account : state => state.account.current
        }),
        created() {
            if(!this.isAuthenticated){
                this.$router.push('/login')
            }
        },
        methods: {
            ...mapActions('account', [
                'update'
            ]),
            ...mapActions('i18n', [
                'setLanguage'
            ]),
            validate : function(){
                this.validEmail = this.validateEmail(this.account.email);
                this.validName = this.validField(this.account.name);
                this.validLanguage = this.validField(this.account.language);

                if(this.validEmail &&
                    this.validName &&
                    this.validLanguage
                ){
                    this.valid = true;
                }else{
                    this.valid = false;
                }
            },
            validField : function(value){
                return value != ''
            },
            validateEmail : function(email){
                const re = /(.+)@(.+){2,}\.(.+){2,}/;
                return re.test(email.toLowerCase());
            },
            submit : function(){
                this.validate();
                if(this.valid){
                    this.update(this.account)

                }
            }
        },
        watch: {
            account (current){
                if(current){
                    this.setLanguage(current.language)
                    this.$router.push('/events')
                }
            }

        }
    }
</script>

<style scoped>

</style>
