// angular-app/src/app/component/register/register.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {AccountService} from "../../service/account.service";
import {Router} from '@angular/router';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Account} from '../../model/account';
import {TranslateService} from "@ngstack/translate";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class RegisterComponent implements OnInit {

  pageTitle: string;
  submitted = false;
  registerForm: FormGroup;
  account : Account;
  debug: boolean = true;

  constructor(private accountService: AccountService,
              private router: Router,
              private formBuilder: FormBuilder,
              private translate: TranslateService) { }

  ngOnInit() {
    this.pageTitle = this.translate.get("title-register");
    this.registerForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      language: ['en', Validators.required],
      name: ['', Validators.required]
    });

    this.account = new Account();
    this.account.email = '';
    this.account._id = '';
    this.account.language = 'en';
    this.account.name = '';
  }

  get form() {
    return this.registerForm.controls;
  }

  onSubmit() {
    this.submitted = true;

    if (this.registerForm.invalid) {
      return;
    }

    this.account._id = this.registerForm.value.accessCode;
    this.account.email = this.registerForm.value.email;
    this.account.language = this.registerForm.value.language;
    this.account.name = this.registerForm.value.name;

    this.accountService.create(this.account)
      .subscribe(account => {
        if(account){
          this.accountService.activeAccount = account;
          this.router.navigate(['/account']);
        }
        //
      })
  }

}

<h2>{{pageTitle}}</h2>

<form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
  <div class="form-group">
    <label>{{ 'field-name' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="name"
      name="name"
      formControlName="name"
      [ngClass]="{ 'is-invalid': submitted && form.name.errors }"
    />
    <div *ngIf="submitted && form.name.errors" class="invalid-feedback">
      <div *ngIf="form.name.errors.required">{{ 'field-name' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>
  <div class="form-group">
    <label>{{ 'field-email' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="email"
      name="email"
      formControlName="email"
      [ngClass]="{ 'is-invalid': submitted && form.email.errors }"
    />
    <div *ngIf="submitted && form.email.errors" class="invalid-feedback">
      {{ 'field-email' | translate }}{{ 'error-required' | translate }}
    </div>
  </div>

  <div class="form-group">
    <label>{{ 'field-language' | translate }}</label>
    <br />
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageEN"
          name="language"
          formControlName="language"
          value="en"
        />
        {{ 'language-en' | translate }}
      </label>
    </div>
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageNL"
          name="language"
          formControlName="language"
          value="nl"
        />
        {{ 'language-nl' | translate }}
      </label>
    </div>
    <div *ngIf="submitted && form.language.errors" class="invalid-feedback">
      <div *ngIf="form.language.errors.required">{{ 'field-language' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>

  <button type="submit" class="btn btn-success float-right">
    {{ 'button-register' | translate }}
  </button>
</form>

<div *ngIf="debug">
  <p>Form value: {{ registerForm.value | json }}</p>
  <p>Form status: {{ registerForm.status | json }}</p>
</div>

// vue-app/src/components/register.vue
<template>
    <div>
        <h2>{{ $t('title-register') }}</h2>
        <div>
            <div class="form-group">
                <label>{{ $t('field-name') }}</label>
                <input
                        v-model="name"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validName}">
                <div class="invalid-feedback">{{ $t('field-name') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-email') }}</label>
                <input
                        v-model="email"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validEmail}">
                <div class="invalid-feedback">{{ $t('field-email') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-language') }}</label>
                <br />
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="en"
                                name="language"
                                v-model="language"
                                value="en"
                        />
                        {{ $t('language-en') }}
                    </label>
                </div>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="nl"
                                name="language"
                                v-model="language"
                                value="nl"
                        />
                        {{ $t('language-nl') }}
                    </label>
                </div>

                <div class="invalid-feedback">{{ $t('field-language') }}{{ $t('error-required') }}</div>
            </div>

            <button type="submit" class="btn btn-success float-right" v-on:click.stop.prevent="submit">
                {{ $t('button-register') }}
            </button>

        </div>

        <div v-if="debug">{email: {{email}}, name: {{name}}, language: {{language}}}</div>
    </div>
</template>

<script>
    import {mapActions, mapState} from "vuex";

    export default {
        name: "register",
        data () {
            return {
                debug : true,
                valid : false,
                validEmail : true,
                validName : true,
                validLanguage : true,
                email : '',
                language : 'en',
                name : ''
            }
        },
        computed: mapState({
            isAuthenticated : state => state.account.authenticated,
            account : state => state.account.current
        }),
        created() {
            /*if(!this.isAuthenticated){
                this.$router.push('/login')
            }*/
        },
        methods: {
            ...mapActions('account', [
                'create'
            ]),
            ...mapActions('i18n', [
                'setLanguage'
            ]),
            validate : function(){
                this.validEmail = this.validateEmail(this.email);
                this.validName = this.validField(this.name);
                this.validLanguage = this.validField(this.language);

                if(this.validEmail &&
                    this.validName &&
                    this.validLanguage
                ){
                    this.valid = true;
                }else{
                    this.valid = false;
                }
            },
            validField : function(value){
                return value != ''
            },
            validateEmail : function(email){
                const re = /(.+)@(.+){2,}\.(.+){2,}/;
                return re.test(email.toLowerCase());
            },
            submit : function(){
                this.validate();
                if(this.valid){
                    let newAccount = {
                        email : this.email,
                        name : this.name,
                        language : this.language
                    }

                    console.log("NEW ACCOUNT: " + JSON.stringify(newAccount))
                    this.create(newAccount)

                }
            }
        },
        watch: {
            account (current){
                if(current){
                    this.setLanguage(current.language)
                    this.$router.push('/account')
                }
            }

        }
    }
</script>

<style scoped>

</style>
