// vue-app/src/components/login.vue
<template>

    <div>
        <h2>{{ $t('title-login') }}</h2>
        <div id="no_account" v-if="showRegister">
            <p>
                <span class="no-account-text">{{ $t('message-info-register') }}</span>
                <router-link to="/register" class="btn btn-primary">{{ $t('button-register') }}</router-link>
            </p>
        </div>
            <div>
                <div class="form-group">

                    <label>{{ $t('field-email') }}</label>

                    <input
                            v-model="email"
                            v-bind:class="{'form-control':true, 'is-invalid' : !validEmail}">
                    <div class="invalid-feedback">{{ $t('field-email') }}{{ $t('error-required') }}</div>
                </div>

                <div class="form-group">
                    <label>{{ $t('field-accessCode') }}</label>
                    <input
                            v-model="accessCode"
                            v-bind:class="{'form-control':true, 'is-invalid' : !validAccessCode}">
                    <div class="invalid-feedback">{{ $t('field-accessCode') }}{{ $t('error-required') }}</div>
                </div>

                <button type="submit" class="btn btn-success float-right" v-on:click.stop.prevent="submit">
                    {{ $t('button-login') }}
                </button>

            </div>
    </div>


</template>

<script>
    import {mapActions, mapState} from "vuex";

    export default {
        name: "login",
        data () {
            return {
                debug : true,
                valid : false,
                validEmail : true,
                validAccessCode : true,
                email : "",
                accessCode : "",
                showRegister : false
            }
        },
        methods: {
            ...mapActions('account', [
                'fetchAccount'
            ]),
            ...mapActions('i18n', [
                'setLanguage'
            ]),
            validate : function(){
                this.validEmail = this.validateEmail(this.email);
                this.validAccessCode = this.validField(this.accessCode);

                if(this.validEmail &&
                    this.validAccessCode
                ){
                    this.valid = true;
                }else{
                    this.valid = false;
                }
            },
            validField : function(value){
                return value != ''
            },
            validateEmail : function(email){
                const re = /(.+)@(.+){2,}\.(.+){2,}/;
                return re.test(email.toLowerCase());
            },
            submit : function(){
                this.validate();
                if(this.valid){
                    let login = {
                        _id: this.accessCode,
                        email : this.email
                    }
                    this.fetchAccount(login)

                }
            }
        },
        computed: mapState({
            account : state => state.account.current,
        }),
        watch: {
            account (current){
                if(current){
                    this.showRegister = false;
                    this.setLanguage(current.language)
                    this.$router.push('/events')
                }else{
                    this.showRegister = true
                }
            }

        }
    }
</script>

<style scoped>

</style>

// angular-app/src/app/component/login/login.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {AccountService} from "../../service/account.service";
import {Router} from '@angular/router';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Account} from '../../model/account';
import {TranslateService} from "@ngstack/translate";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class LoginComponent implements OnInit {

  pageTitle: string;
  submitted:boolean = false;
  loginForm: FormGroup;
  account : Account;
  showRegister : boolean = false;
  debug: boolean = false;

  constructor(private accountService: AccountService,
              private router: Router,
              private formBuilder: FormBuilder,
              private translate: TranslateService) { }

  ngOnInit() {
    this.pageTitle = this.translate.get("title-login");
    this.loginForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      accessCode: ['', Validators.required]
    });

    this.account = new Account();
    this.account.email = '';
    this.account._id = '';
  }

  get form() {
    return this.loginForm.controls;
  }

  onSubmit() {
    this.submitted = true;

    if (this.loginForm.invalid) {
      return;
    }

    this.account._id = this.loginForm.value.accessCode;
    this.account.email = this.loginForm.value.email;

    this.accountService.fetch(this.account)
      .subscribe(account => {
        if(account == null){
          this.showRegister = true;
        }else{
          this.showRegister = false;
          this.accountService.activeAccount = account;
          this.router.navigate(['/events']);
        }
        //
      })
  }

  public setLanguage(language : string){
    this.translate.activeLang = language;
  }

}


<h2>{{pageTitle}}</h2>
<div id="no_account" *ngIf="showRegister">
<p>
  <span class="no-account-text">{{ 'message-info-register' | translate }}</span>
  <a [routerLink]="['/register']" class="btn btn-primary">{{ 'button-register' | translate }}</a>
</p>
</div>
<form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
  <div class="form-group">
    <label>{{ 'field-email' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="email"
      name="email"
      formControlName="email"
      [ngClass]="{ 'is-invalid': submitted && form.email.errors }"
    />
    <div *ngIf="submitted && form.email.errors" class="invalid-feedback">
      <div *ngIf="form.email.errors.required">{{ 'field-email' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>
  <div class="form-group">
    <label for="accessCode">{{ 'field-accessCode' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="accessCode"
      name="accessCode"
      formControlName="accessCode"
      [ngClass]="{ 'is-invalid': submitted && form.accessCode.errors }"
    />
    <div *ngIf="submitted && form.accessCode.errors" class="invalid-feedback">
      <div *ngIf="form.accessCode.errors.required">{{ 'field-accessCode' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>

  <button type="submit" class="btn btn-success float-right">
    {{ 'button-login' | translate }}
  </button>
</form>

<div *ngIf="debug">
  <p>Form value: {{ loginForm.value | json }}</p>
  <p>Form status: {{ loginForm.status | json }}</p>
</div>
