// angular-app/src/app/component/account/account.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {AccountService} from "../../service/account.service";
import {Router} from '@angular/router';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Account} from '../../model/account';
import {TranslateService} from "@ngstack/translate";

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class AccountComponent implements OnInit {

  pageTitle: string;
  submitted = false;
  accountForm: FormGroup;
  accessCode: string;
  debug: boolean = false;

  constructor(private accountService: AccountService,
              private router: Router,
              private formBuilder: FormBuilder,
              private translate: TranslateService) { }

  ngOnInit() {
    this.pageTitle = this.translate.get("title-account");
    if(this.accountService.isAuthenticated()){
      this.accountForm = this.formBuilder.group({
        email: [this.accountService.getAccount().email, [Validators.required, Validators.email]],
        language: [this.accountService.getAccount().language, Validators.required],
        name: [this.accountService.getAccount().name, Validators.required]
      });
      this.accessCode = this.accountService.getAccount()._id;

    }else{
      this.notAuthenticated();
    }
  }

  get form() {
    return this.accountForm.controls;
  }

  onSubmit() {
    this.submitted = true;

    if (this.accountForm.invalid) {
      return;
    }

    let account = new Account();
    account._id = this.accessCode;
    account.email = this.accountForm.value.email;
    account.language = this.accountForm.value.language;
    account.name = this.accountForm.value.name;

    this.accountService.update(account._id, account)
      .subscribe(account => {
          if(account){
            this.accountService.activeAccount = account;
            this.router.navigate(['/events']);
          }
      })
  }

  notAuthenticated(){
    this.router.navigate(['/']);
  }

}


<h2>{{pageTitle}}</h2>

<form [formGroup]="accountForm" (ngSubmit)="onSubmit()">
  <div class="form-group">
    <label>{{ 'field-name' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="name"
      name="name"
      formControlName="name"
      [ngClass]="{ 'is-invalid': submitted && form.name.errors }"
    />
    <div *ngIf="submitted && form.name.errors" class="invalid-feedback">
      <div *ngIf="form.name.errors.required">{{ 'field-name' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>
  <div class="form-group">
    <label>{{ 'field-email' | translate }}</label>
    <input
      class="form-control"
      type="text"
      id="email"
      name="email"
      formControlName="email"
      [ngClass]="{ 'is-invalid': submitted && form.email.errors }"
    />
    <div *ngIf="submitted && form.email.errors" class="invalid-feedback">
      {{ 'field-email' | translate }}{{ 'error-required' | translate }}
    </div>
  </div>
  <div class="form-group">
    <label>{{ 'field-accessCode' | translate }}</label>
    <div class="form-control no-border">
      <span>{{accessCode}}</span>
    </div>
  </div>

  <div class="form-group">
    <label>{{ 'field-language' | translate }}</label>
     <br />
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageEN"
          name="language"
          formControlName="language"
          value="en"
        />
        {{ 'language-en' | translate }}
      </label>
    </div>
    <div class="form-check-inline">
      <label class="form-check-label">
        <input
          class="form-check-input"
          type="radio"
          id="languageNL"
          name="language"
          formControlName="language"
          value="nl"
        />
        {{ 'language-nl' | translate }}
      </label>
    </div>
    <div *ngIf="submitted && form.language.errors" class="invalid-feedback">
      <div *ngIf="form.language.errors.required">{{ 'field-langauge' | translate }}{{ 'error-required' | translate }}</div>
    </div>
  </div>

  <button type="submit" class="btn btn-success float-right">
    {{ 'button-update' | translate }}
  </button>
</form>

<div *ngIf="debug">
<p>Form value: {{ accountForm.value | json }}</p>
<p>Form status: {{ accountForm.status | json }}</p>
</div>

// react-app/src/js/components/container/Account.js
import React, {Component} from 'react'
import connect from "react-redux/es/connect/connect";
import { updateAccount } from '../../actions/account';
import {FormErrors} from "../presentation/FormErrors";
import { Translate, getActiveLanguage } from "react-localize-redux";
import '../presentation/form.css';

const mapStateToProps = state => {
    return { 
        account: state.account,
        currentLanguage: getActiveLanguage(state.localize).code
     };
};

const mapDispatchToProps = dispatch => {
    return {
        updateAccount: (id, account) => dispatch(updateAccount(id, account))
    };
};

class Account extends Component {
    constructor(props){
        super(props);
        this.state = {
            accessCode: props.account ? props.account._id : "",
            email: props.account ? props.account.email : "",
            language: props.account ? props.account.langauge : props.currentLanguage,
            formErrors: {email: ''},
            emailValid: true,
            formValid: true
        }

        this.onSubmit = this.onSubmit.bind(this);
        this.handleEmailInput = this.handleEmailInput.bind(this);
        this.handleLanguageInput = this.handleLanguageInput.bind(this);

        console.log('Current state = '+ JSON.stringify(this.props.account));
    }

    handleEmailInput(e){
        const value = e.target.value;
        this.setState({email: value});
    }

    handleLanguageInput(e){
        const value = e.target.value;
        this.setState({language: value});
    }

    validateField(fieldName, value) {
        let fieldValidationErrors = this.state.formErrors;
        let emailValid = this.state.emailValid;

        switch(fieldName) {
            case 'email':
                emailValid = value.match(/^([\w.%+-]+)@([\w-]+\.)+([\w]{3,})$/i);
                fieldValidationErrors.email = emailValid ? '' : ' is invalid';
                break;
            default:
                break;
        }
        this.setState({formErrors: fieldValidationErrors,
            emailValid: emailValid
        }, this.validateForm);
    }

    validateForm() {
        this.setState({formValid: this.state.emailValid });
    }

    errorClass(error) {
        return(error.length === 0 ? '' : 'has-error');
    }

    onSubmit(e){
        e.preventDefault();

        this.validateField('email', this.state.email);

        if(this.state.formValid){
            let accountUpdate = {
                _id: this.props.account._id,
                email : this.state.email,
                language : this.state.language,
                _class: "nl.elstarit.event.service.model.Account"
            }

            this.props.updateAccount(this.accountUpdate.id, accountUpdate);
        }

    }

    render(){
        return (
            <div>
                <form onSubmit={this.onSubmit}>
                    <h2>Account</h2>
                    { !this.state.formValid ? <FormErrors formErrors={this.state.formErrors} /> : "" }
                    <div className={`form-group ${this.errorClass(this.state.formErrors.email)}`}>
                        <label>Email address</label>
                        <input
                            className="form-control"
                            type="text"
                            id="email"
                            placeholder="Email address"
                            value={this.state.email}
                            onChange={this.handleEmailInput}
                        />
                    </div>
                    <div className="form-group">
                        <label><Translate id="field-accessCode"></Translate></label>
                        <div className="form-control no-border">
                            <span>{this.state.accessCode}</span>
                        </div>
                    </div>
                    <div className={`form-group`}>
                        <label><Translate id="field-language"></Translate></label>
                        <br />
                        <div className="form-check-inline">                   
                            <label className="form-check-label">
                                <input
                                    className="form-check-input"
                                    type="radio"
                                    id="language"
                                    placeholder=""
                                    value="en"
                                    onChange={this.handleLanguageInput}
                                    checked={this.state.language == 'en'}
                                />
                                <Translate id='language-en'></Translate>
                            </label>
                        </div>
                        
                        <div className="form-check-inline"> 
                            <label className="form-check-label">
                                <input
                                    className="form-check-input"
                                    type="radio"
                                    id="language"
                                    placeholder=""
                                    value="nl"
                                    onChange={this.handleLanguageInput}
                                    checked={this.state.language == 'nl'}
                                />
                                <Translate id='language-nl'></Translate>
                            </label>
                        </div>
                    </div>
                    <button type="submit" className="btn btn-success float-right">
                    <Translate id="button-update"></Translate>
                    </button>
                </form>
            </div>
        )
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(Account)
