// angular-app/src/app/component/eventlist/eventlist.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {EventService} from "../../service/event.service";
import {Event} from "../../model/event";
import {AccountService} from "../../service/account.service";
import {Router} from '@angular/router';
import {Payload} from "../../model/payload";
import {CalendarService} from "../../service/calendar.service";
import {FileSaverService} from "ngx-filesaver";
//import saveAs from 'file-saver';

@Component({
  selector: 'app-eventlist',
  templateUrl: './eventlist.component.html',
  styleUrls: ['./eventlist.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class EventlistComponent implements OnInit {

  private events : Event[];

  constructor(private eventService : EventService,
              private router: Router,
              private accountService : AccountService,
              private calendarService : CalendarService,
              private _FileSaverService: FileSaverService) { }

  ngOnInit() {
    if(this.accountService.isAuthenticated()){
      this.loadEvents();
    }else{
      this.notAuthenticated();
    }
  }

  public loadEvents(){
    if(this.accountService.getAccount()) {
      this.eventService.fetchaAllEventsByUserId(this.accountService.getAccount()._id)
        .subscribe(events => this.events = events);
    }
  }

  reloadEvents(){
    this.loadEvents();
  }

  notAuthenticated(){
    this.router.navigate(['/']);
  }

  getDomain(){
    let email = this.accountService.getAccount().email;
    let domain = email.substring(email.indexOf("@") + 1, email.length);
    return domain;
  }

  getTimezone(){
    let timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return timezone;
  }

  exportEvents(){
    let organizer = this.accountService.getAccount().name + " <" + this.accountService.getAccount().email + ">";
      let domain = this.getDomain();
      let timezone = this.getTimezone();

    let payload = new Payload(organizer, domain, timezone);
    payload.setEvents(this.events);

    this.calendarService.createIcal(payload).subscribe(response => {
      this._FileSaverService.save((<any>response), "calendar.ics");
    })

  }

}


<h2>{{ 'title-my-events' | translate }}</h2>
<div *ngIf="!events?.length > 0">
  <p>
    <span class="no-account-text">{{ 'message-no-events' | translate }}</span>
    <a [routerLink]="['/event/add']" class="btn btn-primary">{{ 'button-add-event' | translate }}</a>
  </p>
</div>
<div *ngIf="events?.length > 0">
<div id="export-events" class="button-row1">
  <button class="btn btn-primary float-left" (click)="reloadEvents()">
    {{ 'button-refresh' | translate }}
  </button>
  <button type="submit" class="btn btn-success float-right" (click)="exportEvents()">
    {{ 'button-export' | translate }}
  </button>
</div>
<table class="table">
  <thead>
  <tr>
    <th scope="col">{{ 'column-title' | translate }}</th>
    <th scope="col">{{ 'column-description' | translate }}</th>
    <th scope="col">{{ 'column-location' | translate }}</th>
    <th scope="col">{{ 'column-start-date' | translate }}</th>
    <th scope="col">{{ 'column-end-date' | translate }}</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
    <tr scope="row" *ngFor="let event of events">
      <td>{{event.title}}</td>
      <td>{{event.description}}</td>
      <td>{{event.location}}</td>
      <td>{{event.start | date: 'dd-MM-yyyy'}}</td>
      <td>{{event.end | date: 'dd-MM-yyyy'}}</td>
      <td>
        <a [routerLink]="['/event', event._id]" class="btn btn-warning">{{ 'button-edit' | translate }}</a>
      </td>
      <td>
        <button class="btn btn-danger">{{ 'button-delete' | translate }}</button>
      </td>
    </tr>
  </tbody>
</table>
</div>

// react-app/src/js/components/container/EventList.js
import React, {useEffect, useState} from "react";
import {Link} from 'react-router-dom'
import {Translate} from "react-localize-redux";
import {createIcal} from "../../service/calendar";
import saveAs from 'file-saver';
import useAuth from "../../hooks/useAuth";
import {deleteEvent, fetchAllEventsByUserId} from "../../service/events";

const EventList = () => {
    const { account } = useAuth();
    const [events, setEvents] = useState([])

    useEffect(() => {
        reloadEvents()
    },[]);

    const dEvent = (e, eventId) =>{
        e.preventDefault();
        deleteEvent(eventId)
            .then((response) => {
                reloadEvents()
            }
         )
            .catch((e) => {
                console.log("Delete unsuccessful", e);
            })
    }

    const getDomain = () =>{
        return account.email.substring(account.email.indexOf("@") + 1, account.email.length);
    }

    const getTimezone = () =>{
        return Intl.DateTimeFormat().resolvedOptions().timeZone;
    }

    const reloadEvents = () => {
        fetchAllEventsByUserId(account._id)
            .then((response) => {
                setEvents(response)
            })
            .catch((e) => {
                console.log(e);
            });
    }

    const exportEvents = (e) =>{
        e.preventDefault();

        let payload = {
            organizer: account.name + " <" + account.email + ">",
            domain : getDomain(),
            timezone : getTimezone(),
            events: events
        }

        createIcal(payload).then(response => {
            let blob = new Blob([response.data], {type: "text/calendar;charset=utf-8"});
            saveAs(blob, "calendar.ics");
            })
            .catch(error => {
                throw(error);
            });
    }

    return (
            <div>
                <h2><Translate id="title-my-events"></Translate></h2>
                <div id="no-events" style={{display: (events.length > 0) ? 'none' : 'block' }}  className='alert alert-info'>
                    <Translate id="message-no-events"></Translate>
                </div>
                <div id="export-events" className="button-row1" style={{display: (events.length > 0) ? 'block' : 'none' }}>
                    <button className="btn btn-primary float-left" onClick={(e) => reloadEvents()}>
                        <Translate id="button-refresh"></Translate>
                    </button>
                    <button type="submit" className="btn btn-success float-right" onClick={(e) => exportEvents(e)}>
                        <Translate id="button-export"></Translate>
                    </button>
                </div>

                <table className="table">
                    <thead>
                    <tr>
                        <th scope="col"><Translate id="column-title"></Translate></th>
                        <th scope="col"><Translate id="column-description"></Translate></th>
                        <th scope="col"><Translate id="column-location"></Translate></th>
                        <th scope="col"><Translate id="column-start-date"></Translate></th>
                        <th scope="col"><Translate id="column-end-date"></Translate></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {events && events.map(event => (
                        <tr scope="row" key={event._id}>
                            <td>{event.title}</td>
                            <td>{event.description}</td>
                            <td>{event.location}</td>
                            <td>{new Intl.DateTimeFormat('nl-NL').format(new Date(event.start))}</td>
                            <td>{new Intl.DateTimeFormat('nl-NL').format(new Date(event.end))}</td>
                            <td>
                                <Link className="btn btn-warning" to={`/event/${event._id}`}>
                                    <Translate id="button-edit"></Translate>
                                </Link>
                            </td>
                            <td>
                                <button type="submit" className="btn btn-danger" onClick={(e) => dEvent(e, event._id)}>
                                    <Translate id="button-delete"></Translate>
                                </button>

                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>

            </div>
        )
}
export default EventList;
