// vue-app/src/components/event-list.vue

<template>
        <div>
                <h2>{{ $t('title-my-events') }}</h2>
            <div v-if="showNoEvents">
                <p>
                    <span class="no-account-text">{{ $t('message-no-events') }}</span>
                    <router-link to="//event/add" class="btn btn-primary">{{ $t('button-add-event') }}</router-link>
                </p>
            </div>
            <div v-if="!showNoEvents">
                <div id="export-events" class="button-row1">
                    <button class="btn btn-primary float-left" v-on:click="reloadEvents">
                        {{ $t('button-refresh') }}
                    </button>
                    <button type="submit" class="btn btn-success float-right" v-on:click="exportEvents">
                        {{ $t('button-export') }}
                    </button>
                </div>
                <table class="table">
                        <thead>
                        <tr>
                                <th scope="col">{{ $t('column-title') }}</th>
                                <th scope="col">{{ $t('column-description') }}</th>
                                <th scope="col">{{ $t('column-location') }}</th>
                                <th scope="col">{{ $t('column-start-date') }}</th>
                                <th scope="col">{{ $t('column-end-date') }}</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                                <tr v-for="event in events" :key="event._id" >
                                        <td>{{event.title}}</td>
                                        <td>{{event.description}}</td>
                                        <td>{{event.location}}</td>
                                        <td>{{ format(new Date(event.start), 'dd-MM-yyyy') }}</td>
                                        <td>{{ format(new Date(event.end), 'dd-MM-yyyy') }}</td>
                                        <td>
                                                <router-link :to="{ name: 'event_edit', params: { id: event._id }}" class="btn btn-warning">{{ $t('button-edit') }}</router-link>
                                        </td>
                                        <td>
                                                <button type="submit" class="btn btn-danger" v-on:click="deleteEvent(event)">
                                                        {{ $t('button-delete') }}
                                                </button>
                                        </td>
                                </tr>
                        </tbody>
                </table>
            </div>
        </div>
</template>

<script>
    import {mapActions, mapState} from 'vuex'
    import {createIcal} from "@/service/calendar";
    import FileSaver from 'file-saver';
    import {format} from "date-fns";
    export default {
        name: "eventList",
        data () {
            return {
                showNoEvents : false,
            }
        },
        methods: {
          format,
            ...mapActions('events', [
                'getAllEventsByUserId',
                'deleteEvent'
                ]),
            getDomain(){
                let domain = this.account.email.substring(this.account.email.indexOf("@") + 1, this.account.email.length);
                return domain;
            },

            getTimezone(){
                let timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
                return timezone;
            },
            reloadEvents(){
                this.getAllEventsByUserId(this.account._id);
            },
            exportEvents(){
                let payload = {
                    organizer: this.account.name + " <" + this.account.email + ">",
                    domain : this.getDomain(),
                    timezone : this.getTimezone(),
                    events: this.events
                }

                console.log("Export payload = " + JSON.stringify(payload));
                createIcal(payload).then(response => {
                    let blob = new Blob([response.data], {type: "text/calendar;charset=utf-8"});
                    FileSaver.saveAs(blob, "calendar.ics");
                })
                    .catch(error => {
                        throw(error);
                    });
            }
        },

        computed: {
            ...mapState({
                events : state => state.events.all,
                isAuthenticated : state => state.account.authenticated,
                account : state => state.account.current
            }),
        },


        created (){
            if(!this.isAuthenticated){
                this.$router.push('/login')
            }else{
                this.getAllEventsByUserId(this.account._id);
            }
            this.showNoEvents = this.events.length;
        }
    }
</script>

<style scoped>

</style>

// react-app/src/js/components/container/EventList.js
import React, {useEffect, useState} from "react";
import {Link} from 'react-router-dom'
import {Translate} from "react-localize-redux";
import {createIcal} from "../../service/calendar";
import saveAs from 'file-saver';
import useAuth from "../../hooks/useAuth";
import {deleteEvent, fetchAllEventsByUserId} from "../../service/events";

const EventList = () => {
    const { account } = useAuth();
    const [events, setEvents] = useState([])

    useEffect(() => {
        reloadEvents()
    },[]);

    const dEvent = (e, eventId) =>{
        e.preventDefault();
        deleteEvent(eventId)
            .then((response) => {
                reloadEvents()
            }
         )
            .catch((e) => {
                console.log("Delete unsuccessful", e);
            })
    }

    const getDomain = () =>{
        return account.email.substring(account.email.indexOf("@") + 1, account.email.length);
    }

    const getTimezone = () =>{
        return Intl.DateTimeFormat().resolvedOptions().timeZone;
    }

    const reloadEvents = () => {
        fetchAllEventsByUserId(account._id)
            .then((response) => {
                setEvents(response)
            })
            .catch((e) => {
                console.log(e);
            });
    }

    const exportEvents = (e) =>{
        e.preventDefault();

        let payload = {
            organizer: account.name + " <" + account.email + ">",
            domain : getDomain(),
            timezone : getTimezone(),
            events: events
        }

        createIcal(payload).then(response => {
            let blob = new Blob([response.data], {type: "text/calendar;charset=utf-8"});
            saveAs(blob, "calendar.ics");
            })
            .catch(error => {
                throw(error);
            });
    }

    return (
            <div>
                <h2><Translate id="title-my-events"></Translate></h2>
                <div id="no-events" style={{display: (events.length > 0) ? 'none' : 'block' }}  className='alert alert-info'>
                    <Translate id="message-no-events"></Translate>
                </div>
                <div id="export-events" className="button-row1" style={{display: (events.length > 0) ? 'block' : 'none' }}>
                    <button className="btn btn-primary float-left" onClick={(e) => reloadEvents()}>
                        <Translate id="button-refresh"></Translate>
                    </button>
                    <button type="submit" className="btn btn-success float-right" onClick={(e) => exportEvents(e)}>
                        <Translate id="button-export"></Translate>
                    </button>
                </div>

                <table className="table">
                    <thead>
                    <tr>
                        <th scope="col"><Translate id="column-title"></Translate></th>
                        <th scope="col"><Translate id="column-description"></Translate></th>
                        <th scope="col"><Translate id="column-location"></Translate></th>
                        <th scope="col"><Translate id="column-start-date"></Translate></th>
                        <th scope="col"><Translate id="column-end-date"></Translate></th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {events && events.map(event => (
                        <tr scope="row" key={event._id}>
                            <td>{event.title}</td>
                            <td>{event.description}</td>
                            <td>{event.location}</td>
                            <td>{new Intl.DateTimeFormat('nl-NL').format(new Date(event.start))}</td>
                            <td>{new Intl.DateTimeFormat('nl-NL').format(new Date(event.end))}</td>
                            <td>
                                <Link className="btn btn-warning" to={`/event/${event._id}`}>
                                    <Translate id="button-edit"></Translate>
                                </Link>
                            </td>
                            <td>
                                <button type="submit" className="btn btn-danger" onClick={(e) => dEvent(e, event._id)}>
                                    <Translate id="button-delete"></Translate>
                                </button>

                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>

            </div>
        )
}
export default EventList;
