// vue-app/src/components/register.vue
<template>
    <div>
        <h2>{{ $t('title-register') }}</h2>
        <div>
            <div class="form-group">
                <label>{{ $t('field-name') }}</label>
                <input
                        v-model="name"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validName}">
                <div class="invalid-feedback">{{ $t('field-name') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-email') }}</label>
                <input
                        v-model="email"
                        v-bind:class="{'form-control':true, 'is-invalid' : !validEmail}">
                <div class="invalid-feedback">{{ $t('field-email') }}{{ $t('error-required') }}</div>
            </div>

            <div class="form-group">
                <label>{{ $t('field-language') }}</label>
                <br />
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="en"
                                name="language"
                                v-model="language"
                                value="en"
                        />
                        {{ $t('language-en') }}
                    </label>
                </div>
                <div class="form-check-inline">
                    <label class="form-check-label">
                        <input
                                class="form-check-input"
                                type="radio"
                                id="nl"
                                name="language"
                                v-model="language"
                                value="nl"
                        />
                        {{ $t('language-nl') }}
                    </label>
                </div>

                <div class="invalid-feedback">{{ $t('field-language') }}{{ $t('error-required') }}</div>
            </div>

            <button type="submit" class="btn btn-success float-right" v-on:click.stop.prevent="submit">
                {{ $t('button-register') }}
            </button>

        </div>

        <div v-if="debug">{email: {{email}}, name: {{name}}, language: {{language}}}</div>
    </div>
</template>

<script>
    import {mapActions, mapState} from "vuex";

    export default {
        name: "register",
        data () {
            return {
                debug : true,
                valid : false,
                validEmail : true,
                validName : true,
                validLanguage : true,
                email : '',
                language : 'en',
                name : ''
            }
        },
        computed: mapState({
            isAuthenticated : state => state.account.authenticated,
            account : state => state.account.current
        }),
        created() {
            /*if(!this.isAuthenticated){
                this.$router.push('/login')
            }*/
        },
        methods: {
            ...mapActions('account', [
                'create'
            ]),
            ...mapActions('i18n', [
                'setLanguage'
            ]),
            validate : function(){
                this.validEmail = this.validateEmail(this.email);
                this.validName = this.validField(this.name);
                this.validLanguage = this.validField(this.language);

                if(this.validEmail &&
                    this.validName &&
                    this.validLanguage
                ){
                    this.valid = true;
                }else{
                    this.valid = false;
                }
            },
            validField : function(value){
                return value != ''
            },
            validateEmail : function(email){
                const re = /(.+)@(.+){2,}\.(.+){2,}/;
                return re.test(email.toLowerCase());
            },
            submit : function(){
                this.validate();
                if(this.valid){
                    let newAccount = {
                        email : this.email,
                        name : this.name,
                        language : this.language
                    }

                    console.log("NEW ACCOUNT: " + JSON.stringify(newAccount))
                    this.create(newAccount)

                }
            }
        },
        watch: {
            account (current){
                if(current){
                    this.setLanguage(current.language)
                    this.$router.push('/account')
                }
            }

        }
    }
</script>

<style scoped>

</style>

// react-app/src/js/components/container/Register.js
import React, {Component} from 'react'
import { Link } from 'react-router-dom'
import connect from "react-redux/es/connect/connect";
import {createAccount} from "../../actions/account";
import { Translate, getActiveLanguage } from "react-localize-redux";

const mapStateToProps = state => {
    return { 
        account: state.account,
        currentLanguage: getActiveLanguage(state.localize).code
    };
};

const mapDispatchToProps = dispatch => {
    return {
        createAccount: (account) => dispatch(createAccount(account))
    };
};

class Register extends Component {
    constructor(props){
        super(props);
        this.state = {
            email: "",//props.account ? props.account.email : "",
            language: props.currentLanguage,
            formErrors: {email: ''},
            emailValid: true,
            formValid: true,
        }

        this.onSubmit = this.onSubmit.bind(this);
        this.handleEmailInput = this.handleEmailInput.bind(this);
        this.handleLanguageInput = this.handleLanguageInput.bind(this);
    }

    handleEmailInput(e){
        const value = e.target.value;
        this.setState({email: value});
    }

    handleLanguageInput(e){
        const value = e.target.value;
        this.setState({language: value});
    }

    validateField(fieldName, value) {
        let fieldValidationErrors = this.state.formErrors;
        let emailValid = this.state.emailValid;

        switch(fieldName) {
            case 'email':
                emailValid = value.match(/^([\w.%+-]+)@([\w-]+\.)+([\w]{3,})$/i);
                fieldValidationErrors.email = emailValid ? '' : 'error-required';
                break;
            default:
                break;
        }
        this.setState({formErrors: fieldValidationErrors,
            emailValid: emailValid
        }, this.validateForm);
    }

    validateForm() {
        this.setState({formValid: this.state.emailValid });
    }

    errorClass(error) {
        return(error.length === 0 ? '' : 'has-error');
    }

    isFormValid(){
        return JSON.stringify(this.state.formErrors).indexOf('error-required') < 0
    }

    onSubmit(e){

        e.preventDefault();

        this.validateField('email', this.state.email);
        if(this.isFormValid()){
            let account = {
                email : this.state.email,
                language : this.state.language,
                _class: "nl.elstarit.event.service.model.Account"
            }
            //this.props.createAccount(account);
        }

    }

    render(){
        console.log("Active language: " + this.state.language);
        return (
            <div>
                <form onSubmit={this.onSubmit}>
                    <h2><Translate id="title-register"></Translate></h2>
                    { !this.state.formValid ? <FormErrors formErrors={this.state.formErrors} /> : "" }
                    <div className={`form-group ${this.errorClass(this.state.formErrors.email)}`}>
                        <label><Translate id="field-email"></Translate></label>
                        <input
                            className="form-control"
                            type="text"
                            id="email"
                            placeholder=""
                            value={this.state.email}
                            onChange={this.handleEmailInput}
                        />
                    </div>
                    <div className={`form-group`}>
                        <label><Translate id="field-language"></Translate></label>
                        <br />
                        <div className="form-check-inline">                   
                            <label className="form-check-label">
                                <input
                                    className="form-check-input"
                                    type="radio"
                                    id="language"
                                    placeholder=""
                                    value="en"
                                    onChange={this.handleLanguageInput}
                                    checked={this.state.language == 'en'}
                                />
                                <Translate id='language-en'></Translate>
                            </label>
                        </div>
                        
                        <div className="form-check-inline"> 
                            <label className="form-check-label">
                                <input
                                    className="form-check-input"
                                    type="radio"
                                    id="language"
                                    placeholder=""
                                    value="nl"
                                    onChange={this.handleLanguageInput}
                                    checked={this.state.language == 'nl'}
                                />
                                <Translate id='language-nl'></Translate>
                            </label>
                        </div>
                    </div>
                    <button type="submit" className="btn btn-success float-right">
                    <Translate id="button-register"></Translate>
                    </button>
                </form>
            </div>
        )
    }
}

export default connect(mapStateToProps,mapDispatchToProps)(Register)
