// vue-app/src/components/edit-event.vue
<template>
    <div>
        <h2>{{ $t('title-edit-event') }}</h2>
            <div>
                <div class="form-group">
                    <label>{{ $t('field-title') }}</label>
                    <input
                            v-model="event.title"
                            v-bind:class="{'form-control':true, 'is-invalid' : !validTitle}">
                    <div class="invalid-feedback">{{ $t('field-title') }}{{ $t('error-required') }}</div>
                </div>

                <div class="form-group">
                    <label>{{ $t('field-description') }}</label>
                    <input
                            v-model="event.description"
                            v-bind:class="{'form-control':true, 'is-invalid' : !validDescription}">
                    <div class="invalid-feedback">{{ $t('field-description') }}{{ $t('error-required') }}</div>
                </div>

                <div class="form-group">
                    <label>{{ $t('field-location') }}</label>
                    <input
                            v-model="event.location"
                            v-bind:class="{'form-control':true, 'is-invalid' : !validLocation}">
                    <div class="invalid-feedback">{{ $t('field-location') }}{{ $t('error-required') }}</div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            <label style="margin-right: 10px">{{ $t('field-start-date') }}</label>
                            <VueDatePicker
                                    v-model="startDate"
                                    lang="en"
                                    type="date"
                                    format="dd-MM-yyyy">
                            </VueDatePicker>
                            <div class="invalid-feedback">{{ $t('field-start-date') }}{{ $t('error-required') }}</div>
                        </div>
                        <div class="col-6">
                            <label style="margin-right: 10px">{{ $t('field-end-date') }}</label>
                            <VueDatePicker
                                    v-model="endDate"
                                    lang="en"
                                    type="date"
                                    format="dd-MM-yyyy">
                            </VueDatePicker>
                            <div class="invalid-feedback">{{ $t('field-end-date') }}{{ $t('error-required') }}</div>
                        </div>
                    </div>
                </div>
                <router-link to="/events" class="btn btn-primary">{{ $t('button-back') }}</router-link>
                <button type="submit" class="btn btn-success float-right" v-on:click.stop.prevent="submit">
                    {{ $t('button-save') }}
                </button>
            </div>


        <div >{{event}}</div>
    </div>
</template>

<script>
    import {mapActions, mapGetters, mapState} from "vuex";
    import VueDatePicker from '@vuepic/vue-datepicker';
    import '@vuepic/vue-datepicker/dist/main.css';

    export default {
        name: "editEvent",
        components: { VueDatePicker },
        data () {
            return {
                debug : true,
                eventId: 0,
                valid : false,
                submitted : false,
                validTitle : true,
                validDescription : true,
                validLocation : true,
                validStartDate : true,
                validEndDate : true
            }
        },
        methods: {
            updateEvent(event) {
                this.updateEvent(event)
            },
            ...mapActions('events', [
                'updateEvent'
            ]),
            validate : function(){
                this.validTitle = this.validField(this.event.title);
                this.validDescription = this.validField(this.event.description);
                this.validLocation = this.validField(this.event.location);
                this.validStartDate = this.validField(this.event.start);
                this.validEndDate = this.validField(this.event.end);

                if(this.validTitle &&
                    this.validDescription &&
                    this.validLocation &&
                    this.validStartDate &&
                    this.validEndDate
                    ){
                    this.valid = true;
                }else{
                    this.valid = false;
                }
            },
            validField : function(value){
                return value !== ''
            },
            submit : function(){
                this.validate();
                if(this.valid){
                    this.submitted = true;
                    this.updateEvent(this.event)
                        .then(
                            this.$router.push("/events")
                        )

                }
            }
        },
        created() {
            this.eventId = this.$route.params.id;
            if(!this.isAuthenticated){
                this.$router.push('/login')
            }
        },
        computed: {
            ...mapGetters('events', ['getEventById']),
            event: function () {
                return this.getEventById(this.$route.params.id);
            },
            startDate:{
                get: function () {
                    return new Date(this.getEventById(this.eventId).start)
                },
                set: function (newValue){
                    this.event.start = new Date(newValue).getTime()
                }
            },
            endDate:{
                get: function () {
                    return new Date(this.getEventById(this.eventId).end)
                },
                set: function (newValue){
                    this.event.end = new Date(newValue).getTime()
                }
            },
            ...mapState({
                isAuthenticated : state => state.account.authenticated,
                account : state => state.account.current,
                locale : state => state.i18n.locale
            }),
        }
    }
</script>

<style scoped>

</style>

// angular-app/src/app/component/edit-event/edit-event.component.ts
import {Component, Input, OnInit, ViewEncapsulation} from '@angular/core';
import {ActivatedRoute} from "@angular/router";
import {EventService} from "../../service/event.service";
import {Event} from "../../model/event";
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import {AccountService} from "../../service/account.service";
import {TranslateService} from "@ngstack/translate";

@Component({
  selector: 'app-edit-event',
  templateUrl: './edit-event.component.html',
  styleUrls: ['./edit-event.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class EditEventComponent implements OnInit {
  pageTitle: string;
  _id: string;
  private sub: any;
  event : Event;
  submitted = false;
  eventForm: FormGroup;

  constructor(private route: ActivatedRoute,
              private eventService : EventService,
              private router: Router,
              private formBuilder: FormBuilder,
              private accountService : AccountService,
              private translate: TranslateService) { }

  ngOnInit() {
    this.pageTitle = this.translate.get("title-edit-event");
    if(this.accountService.isAuthenticated()) {
      this.sub = this.route.params.subscribe(params => {
        this._id = params['id'];
        this.loadEvent();
      });
    }else{
      this.notAuthenticated();
    }

  }

  loadEvent(){
    this.eventService.fetchById(this._id)
      .subscribe( event => {
        this.event = event;

        this.eventForm = this.formBuilder.group({
          title: [this.event.title, Validators.required],
          description: [this.event.description, Validators.required],
          location: [this.event.location, [Validators.required]],
          startDate: [new Date(this.event.start), [Validators.required]],
          endDate: [new Date(this.event.end), [Validators.required]]
        });
      });
  }

  get form() { return this.eventForm.controls; }

  onSubmit() {
    this.submitted = true;

    if (this.eventForm.invalid) {
      return;
    }

    this.event.end = this.eventForm.value.endDate.getTime();
    this.event.start = this.eventForm.value.startDate.getTime();
    this.event.location = this.eventForm.value.location;
    this.event.description = this.eventForm.value.description;
    this.event.title = this.eventForm.value.title;

    this.eventService.update(this.event._id, this.event)
      .subscribe( event => {
        this.event = event;
        this.router.navigate(['/events']);
        })
  }

  notAuthenticated(){
    this.router.navigate(['/']);
  }

}

<div *ngIf="event">
  <h2>{{pageTitle}}</h2>
  <form [formGroup]="eventForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label>{{ 'field-title' | translate }}</label>
      <input
        class="form-control"
        type="text"
        id="title"
        name="title"
        formControlName="title"
        [ngClass]="{ 'is-invalid': submitted && form.title.errors }"
      />
      <div *ngIf="submitted && form.title.errors" class="invalid-feedback">
        <div *ngIf="form.title.errors.required">{{ 'field-title' | translate }}{{ 'error-required' | translate }}</div>
      </div>
    </div>
    <div class="form-group">
      <label for="description">{{ 'field-description' | translate }}</label>
      <input
        class="form-control"
        type="text"
        id="description"
        name="description"
        formControlName="description"
        [ngClass]="{ 'is-invalid': submitted && form.description.errors }"
      />
      <div *ngIf="submitted && form.description.errors" class="invalid-feedback">
        <div *ngIf="form.description.errors.required">{{ 'field-description' | translate }}{{ 'error-required' | translate }}</div>
      </div>
    </div>
    <div class="form-group">
      <label for="location">{{ 'field-location' | translate }}</label>
      <input
        class="form-control"
        type="text"
        id="location"
        name="location"
        formControlName="location"
        [ngClass]="{ 'is-invalid': submitted && form.location.errors }"
      />
      <div *ngIf="submitted && form.location.errors" class="invalid-feedback">
        <div *ngIf="form.location.errors.required">{{ 'field-location' | translate }}{{ 'error-required' | translate }}</div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-6">
          <label style="margin-right: 10px">
            {{ 'field-start-date' | translate }}
          </label>
          <input
            class="form-control"
            type="text"
            id="start_date"
            name="start_date"
            bsDatepicker
            formControlName="startDate"
            [ngClass]="{ 'is-invalid': submitted && form.startDate.errors }"
          />
          <div *ngIf="submitted && form.startDate.errors" class="invalid-feedback">
            <div *ngIf="form.startDate.errors.required">Start date {{ 'error-required' | translate }}</div>
          </div>
        </div>
        <div class="col-6">
          <label  style="margin-right: 10px">
            {{ 'field-end-date' | translate }}
          </label>
          <input
            class="form-control"
            type="text"
            id="end_date"
            name="end_date"
            bsDatepicker
            formControlName="endDate"
            [ngClass]="{ 'is-invalid': submitted && form.endDate.errors }"
          />
          <div *ngIf="submitted && form.endDate.errors" class="invalid-feedback">
            <div *ngIf="form.endDate.errors.required">{{ 'field-end-date' | translate }}{{ 'error-required' | translate }}</div>
          </div>
        </div>
      </div>
    </div>
    <a [routerLink]="['/events']" class="btn btn-primary">{{ 'button-back' | translate }}</a>
    <button type="submit" class="btn btn-success float-right">
      {{ 'button-save' | translate }}
    </button>
  </form>

</div>
